
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[286] =
    {   0,
        0,    0,   78,   76,   73,   75,   74,   76,   76,   76,
       61,   66,   69,   64,   52,   63,   53,   68,   45,   51,
       67,   62,   55,   58,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   59,   65,   72,   56,    0,   50,
       48,    0,    0,    0,   71,   70,   54,   44,   43,    0,
       45,   46,   60,   57,   42,   42,   42,   42,   42,   42,
       42,    6,   42,   42,   42,   42,   42,   42,   42,   16,
       17,   42,   42,   42,   42,   23,   24,   42,   42,   42,
       42,   42,   42,   35,   42,   42,   42,   42,   42,    0,

       49,    0,    0,   48,    0,   47,    0,   44,    1,   42,
       42,   42,   42,    5,   42,   42,    9,   42,   42,   12,
       42,   42,   42,   42,   20,   21,   22,   42,   42,   42,
       42,   42,   42,   33,   42,   42,   42,   38,   42,   42,
        0,   49,    0,    0,    0,   44,    0,   42,   42,    3,
       42,   42,    8,   42,   28,   42,   42,   15,   42,   42,
       42,   42,   42,   42,   41,   42,   42,   34,   36,   42,
       42,   40,   44,    0,   44,   42,   27,    4,   42,   42,
       42,   42,   42,   19,   42,   42,   42,   42,   42,   42,
       37,   39,   44,    0,    0,    7,   10,   42,   42,   42,

       42,   26,   42,   42,   31,   32,    0,    0,    0,   42,
       13,   42,   18,   42,   42,   30,    0,    0,    0,    0,
       11,   14,   42,   42,    0,    0,    0,    0,    0,    0,
       25,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    1,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       32,   39,   40,   41,   42,   43,   44,   45,   46,   32,
       47,   48,   49,   50,   32,    1,   23,   24,   25,   51,

       52,   28,   29,   30,   53,   32,   33,   34,   35,   36,
       37,   38,   32,   39,   40,   41,   42,   43,   44,   45,
       46,   32,   54,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    4,
        3,    3,    3,    1
    } ;

static yyconst flex_uint16_t yy_base[292] =
    {   0,
        0,    0,  510,  511,  511,  511,  511,  488,   52,  500,
      496,  511,  495,  511,  511,  511,   41,  489,   45,  483,
      511,  482,  511,  481,   25,   30,   40,   34,   33,   37,
      464,    0,   44,  477,  462,   39,   45,   52,   54,   56,
       58,  462,  474,   63,  511,  511,  511,  511,   82,   59,
      511,   94,  488,  487,  511,  511,  511,   82,  511,  477,
       81,  511,  511,  511,    0,   76,  454,  463,  451,  454,
      446,  444,  447,   77,  445,  451,  445,  447,  441,    0,
      440,  456,   84,  445,  437,    0,    0,  447,  451,  438,
       88,  433,   85,    0,  435,  431,  432,   83,  429,   98,

      511,  108,  114,  115,  116,  461,  117,  116,    0,  445,
       94,   93,  427,    0,  430,   97,    0,  113,  121,  421,
      439,  426,  123,  124,    0,    0,    0,  125,  429,  128,
      427,  423,  127,    0,  423,  128,  107,    0,  424,  427,
      134,  152,  154,  152,  437,  157,  396,  398,  402,    0,
      395,  394,    0,  395,    0,  410,  391,    0,  402,  396,
      390,  141,  144,  388,    0,  386,  399,    0,    0,  387,
      151,    0,  402,  401,  511,  176,    0,    0,  380,  378,
      373,  154,  156,    0,  366,  160,  161,  386,  162,  367,
        0,    0,  389,  184,  201,    0,  381,  164,  366,  359,

      164,    0,  349,  355,    0,    0,  217,  363,  221,  342,
        0,  326,    0,  310,  301,    0,  222,  186,  235,  227,
        0,    0,  172,  193,  206,  239,  247,  252,  253,  258,
        0,    0,  231,  316,  266,  281,  271,  272,  285,  286,
      290,  291,  304,  311,  305,  308,  309,  321,  322,  326,
      310,  310,  337,  339,  343,  340,  356,  341,  283,  348,
      287,  362,  246,  363,  364,  265,  377,  384,  239,  229,
      220,  379,  220,  200,  210,  205,  368,  185,  164,  169,
      511,  392,  372,  158,  511,  439,  442,  136,  445,  448,
      452

    } ;

static yyconst flex_int16_t yy_def[292] =
    {   0,
      285,    1,  285,  285,  285,  285,  285,  285,  286,  287,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  285,  285,  285,  285,  286,  289,
      285,  290,  287,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  289,

      285,  291,  286,  286,  290,  285,  285,  285,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      289,  289,  291,  285,  285,  285,  285,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  285,  285,  285,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  285,  285,  285,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  285,  285,  285,  288,
      288,  288,  288,  288,  288,  288,  285,  285,  285,  285,
      288,  288,  288,  288,  285,  285,  285,  285,  285,  285,
      288,  288,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,    0,  285,  285,  285,  285,  285,
      285

    } ;

static yyconst flex_uint16_t yy_nxt[566] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   32,   32,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   32,   32,   45,    4,   46,    4,
       28,   29,   33,   47,   50,   57,   68,   58,   51,   60,
       66,   61,   69,   67,   71,  101,   73,   76,   74,   84,
       72,   80,   86,   77,   89,   85,   70,   75,   78,   81,
       91,   68,   92,   87,   50,   88,   71,   93,   51,   76,
       90,   84,   98,   99,   94,   60,   50,   61,   58,   52,

      104,  109,  117,   95,  101,   91,  102,   92,  107,  125,
      131,  135,  132,  139,  142,   99,   50,   50,   50,  150,
       51,   51,  104,  153,  149,  133,  109,  117,  144,   52,
      144,  145,  108,  146,  125,  139,  135,  170,   65,  154,
      101,  105,  107,   49,  150,  102,  149,  155,  153,  159,
      160,  161,  163,  167,  169,  143,  164,  100,  101,  170,
      142,   52,   52,  105,  154,   49,  145,  186,  146,  147,
      187,  174,  155,  146,  159,  160,  161,  192,  167,  169,
      194,  102,  200,  194,  199,  202,  203,  205,  194,  211,
      218,  194,  186,  219,  214,  187,  281,  283,  231,  102,

      225,  143,  192,  100,  147,  207,  199,  200,  207,  282,
      202,  203,  205,  229,  211,  208,  214,  209,  281,  232,
      229,  207,  195,  231,  207,  218,  218,  279,  219,  219,
      195,  208,  278,  209,  229,  220,  225,  209,  217,  218,
      277,  229,  227,  230,  232,  234,  275,  235,  226,  228,
      233,  237,  233,  234,  238,  235,  241,  241,  276,  242,
      241,  239,  218,  240,  274,  219,  243,  244,  240,  240,
      218,  275,  225,  219,  230,  237,  237,  273,  248,  238,
      246,  272,  235,  236,  226,  249,  239,  240,  240,  241,
      251,  236,  242,  251,  241,  241,  267,  241,  241,  243,

      252,  250,  240,  265,  244,  244,  240,  240,  241,  218,
      264,  241,  219,  218,  251,  229,  219,  251,  244,  225,
      250,  245,  229,  225,  255,  237,  257,  254,  238,  229,
      251,  247,  245,  251,  253,  239,  229,  240,  254,  224,
      252,  258,  250,  251,  258,  258,  251,  218,  258,  223,
      219,  260,  256,  260,  261,  254,  262,  225,  253,  255,
      251,  222,  261,  251,  262,  256,  251,  268,  251,  251,
      268,  251,  257,  259,  253,  221,  266,  259,  262,  217,
      265,  251,  256,  251,  251,  269,  251,  253,  268,  216,
      215,  268,  263,  270,  280,  272,  194,  213,  284,  194,

      263,  271,  212,  210,  253,  193,  269,  206,  204,  201,
      253,  198,  253,  197,  270,  270,  196,  193,  173,  280,
      191,  190,  271,  284,  189,  253,  188,  253,  185,  184,
      183,  182,  181,  180,  179,  178,  270,  177,  195,   49,
       49,   49,   53,  176,   53,  100,  175,  100,  103,  103,
      103,  103,  141,  173,  141,  141,  172,  171,  168,  166,
      165,  162,  158,  157,  156,  152,  151,  148,   53,  140,
      138,  137,  136,  134,  130,  129,  128,  127,  126,  124,
      123,  122,  121,  120,  119,  118,  116,  115,  114,  113,
      112,  111,  110,  108,   53,  106,   97,   96,   83,   82,

       79,   64,   63,   62,   59,   56,   55,   54,   48,  285,
        3,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285
    } ;

static yyconst flex_int16_t yy_chk[566] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   17,   26,   17,    9,   19,
       25,   19,   27,   25,   28,   50,   29,   30,   29,   36,
       28,   33,   37,   30,   38,   36,   27,   29,   30,   33,
       39,   26,   40,   37,   49,   37,   28,   41,   49,   30,
       38,   36,   44,   44,   41,   61,   52,   61,   58,    9,

       52,   66,   74,   41,  100,   39,   50,   40,   58,   83,
       91,   93,   91,   98,  102,   44,  103,  104,  105,  112,
      103,  104,  105,  116,  111,   91,   66,   74,  107,   49,
      107,  107,  108,  107,   83,   98,   93,  137,  288,  118,
      141,   52,  108,   52,  112,  100,  111,  119,  116,  123,
      124,  128,  130,  133,  136,  102,  130,  102,  142,  137,
      143,  103,  104,  105,  118,  105,  144,  162,  144,  107,
      163,  146,  119,  146,  123,  124,  128,  171,  133,  136,
      176,  141,  183,  176,  182,  186,  187,  189,  194,  198,
      218,  194,  162,  218,  201,  163,  284,  280,  223,  142,

      218,  143,  171,  143,  144,  195,  182,  183,  195,  279,
      186,  187,  189,  225,  198,  195,  201,  195,  278,  224,
      225,  207,  176,  223,  207,  209,  217,  276,  209,  217,
      194,  207,  275,  207,  220,  209,  217,  209,  217,  219,
      274,  220,  219,  220,  224,  233,  271,  233,  217,  219,
      226,  227,  226,  226,  227,  226,  228,  229,  273,  228,
      229,  227,  230,  227,  270,  230,  228,  229,  228,  229,
      235,  271,  230,  235,  230,  237,  238,  269,  237,  238,
      235,  266,  235,  233,  230,  237,  238,  237,  238,  239,
      240,  226,  239,  240,  241,  242,  263,  241,  242,  239,

      240,  239,  240,  261,  241,  242,  241,  242,  243,  245,
      259,  243,  245,  247,  251,  246,  247,  251,  243,  245,
      243,  245,  246,  247,  246,  248,  252,  244,  248,  249,
      250,  236,  234,  250,  240,  248,  249,  248,  249,  215,
      250,  253,  250,  254,  253,  258,  254,  255,  258,  214,
      255,  256,  250,  256,  256,  254,  256,  255,  251,  255,
      257,  212,  260,  257,  260,  254,  262,  264,  265,  262,
      264,  265,  257,  253,  250,  210,  262,  258,  262,  208,
      265,  267,  257,  272,  267,  264,  272,  254,  268,  204,
      203,  268,  256,  264,  277,  272,  282,  200,  283,  282,

      260,  264,  199,  197,  257,  193,  268,  190,  188,  185,
      262,  181,  265,  180,  268,  264,  179,  174,  173,  277,
      170,  167,  268,  283,  166,  267,  164,  272,  161,  160,
      159,  157,  156,  154,  152,  151,  268,  149,  282,  286,
      286,  286,  287,  148,  287,  289,  147,  289,  290,  290,
      290,  290,  291,  145,  291,  291,  140,  139,  135,  132,
      131,  129,  122,  121,  120,  115,  113,  110,  106,   99,
       97,   96,   95,   92,   90,   89,   88,   85,   84,   82,
       81,   79,   78,   77,   76,   75,   73,   72,   71,   70,
       69,   68,   67,   60,   54,   53,   43,   42,   35,   34,

       31,   24,   22,   20,   18,   13,   11,   10,    8,    3,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "standard-pascal-no-yacc.l"
#line 2 "standard-pascal-no-yacc.l"
/*
 * scan.l
 *
 * lex input file for pascal scanner
 *
 * extensions: two ways to spell "external" and "->" ok for "^".
 */

 #include <stdio.h>

#define true 1
#define false 0

#define   AND      1
#define   ARRAY      2
#define   CASE      3
#define   CONST      4
#define   DIV      5
#define   DO      6
#define   DOWNTO      7
#define   ELSE      8
#define   END      9

#define   EXTERNAL      10
#define   FOR      11
#define   FORWARD      12
#define   FUNCTION      13
#define   GOTO      14
#define   IF      15
#define   IN      16
#define   LABEL      17
#define   MOD      18
#define   NIL      19
#define   NOT      20
#define   OF       21
#define   OR      22
#define   OTHERWISE      23
#define   PACKED      24
#define   PBEGIN      25
#define   PFILE      26
#define   PROCEDURE      27
#define   PROGRAM      28
#define   RECORD      29
#define   REPEAT      30
#define   SET      31
#define   THEN      32
#define   TO      33
#define   TYPE      34
#define   UNTIL      35
#define   VAR      36
#define   WHILE      37
#define   WITH      38
#define   IDENTIFIER      39

#define   ASSIGNMENT      40
#define   CHARACTER_STRING      41
#define   COLON      42
#define   COMMA      43
#define   DIGSEQ      44
#define   DOT      45
#define   DOTDOT      46
#define   EQUAL      47
#define   GE      48
#define   GT      49
#define   LBRAC      50
#define   LE      51
#define   LPAREN      52
#define   LT      53
#define   MINUS      54
#define   NOTEQUAL      55
#define   PLUS      56
#define   RBRAC      57
#define   REALNUMBER      58
#define   RPAREN      59
#define   SEMICOLON      60
#define   SLASH      61
#define   STAR      62
#define   STARSTAR      63

#define   notEQUAL    65

#define COMMENT 100

#define NUM 66
#define INTEGER 67
#define REAL 68
#define CROSS_LINE_STRING 69

int i;
int line_no = 1;


/* integer	 [-]?[[:space:]]*{Digit}+ */
#line 780 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 140 "standard-pascal-no-yacc.l"


#line 1001 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 286 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 511 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 142 "standard-pascal-no-yacc.l"
return(AND);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 143 "standard-pascal-no-yacc.l"
return(ARRAY);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 145 "standard-pascal-no-yacc.l"
return(CASE);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 146 "standard-pascal-no-yacc.l"
return(CONST);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "standard-pascal-no-yacc.l"
return(DIV);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 148 "standard-pascal-no-yacc.l"
return(DO);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "standard-pascal-no-yacc.l"
return(DOWNTO);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "standard-pascal-no-yacc.l"
return(ELSE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 151 "standard-pascal-no-yacc.l"
return(END);
	YY_BREAK
case 10:
#line 153 "standard-pascal-no-yacc.l"
case 11:
YY_RULE_SETUP
#line 153 "standard-pascal-no-yacc.l"
return(EXTERNAL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "standard-pascal-no-yacc.l"
return(FOR);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "standard-pascal-no-yacc.l"
return(FORWARD);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 "standard-pascal-no-yacc.l"
return(FUNCTION);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "standard-pascal-no-yacc.l"
return(GOTO);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 158 "standard-pascal-no-yacc.l"
return(IF);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "standard-pascal-no-yacc.l"
return(IN);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 161 "standard-pascal-no-yacc.l"
return(INTEGER);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "standard-pascal-no-yacc.l"
return(LABEL);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 164 "standard-pascal-no-yacc.l"
return(MOD);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 165 "standard-pascal-no-yacc.l"
return(NIL);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 166 "standard-pascal-no-yacc.l"
return(NOT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 167 "standard-pascal-no-yacc.l"
return(OF);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 168 "standard-pascal-no-yacc.l"
return(OR);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 169 "standard-pascal-no-yacc.l"
return(OTHERWISE);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 170 "standard-pascal-no-yacc.l"
return(PACKED);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 171 "standard-pascal-no-yacc.l"
return(PBEGIN);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 172 "standard-pascal-no-yacc.l"
return(PFILE);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 173 "standard-pascal-no-yacc.l"
return(PROCEDURE);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 174 "standard-pascal-no-yacc.l"
return(PROGRAM);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 175 "standard-pascal-no-yacc.l"
return(RECORD);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 176 "standard-pascal-no-yacc.l"
return(REPEAT);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 177 "standard-pascal-no-yacc.l"
return(SET);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 178 "standard-pascal-no-yacc.l"
return(THEN);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 179 "standard-pascal-no-yacc.l"
return(TO);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 180 "standard-pascal-no-yacc.l"
return(TYPE);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 181 "standard-pascal-no-yacc.l"
return(UNTIL);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 182 "standard-pascal-no-yacc.l"
return(VAR);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 183 "standard-pascal-no-yacc.l"
return(WHILE);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 184 "standard-pascal-no-yacc.l"
return(WITH);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 186 "standard-pascal-no-yacc.l"
return(REAL);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 188 "standard-pascal-no-yacc.l"
return(IDENTIFIER);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 192 "standard-pascal-no-yacc.l"
{ comment(); return(COMMENT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 193 "standard-pascal-no-yacc.l"
return(NUM);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 194 "standard-pascal-no-yacc.l"
return(NUM);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 197 "standard-pascal-no-yacc.l"
return(ASSIGNMENT);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 198 "standard-pascal-no-yacc.l"
return(CHARACTER_STRING);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 201 "standard-pascal-no-yacc.l"
return(CHARACTER_STRING);
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 202 "standard-pascal-no-yacc.l"
return(CROSS_LINE_STRING);
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 203 "standard-pascal-no-yacc.l"
return(CROSS_LINE_STRING);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 205 "standard-pascal-no-yacc.l"
return(COLON);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 206 "standard-pascal-no-yacc.l"
return(COMMA);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 208 "standard-pascal-no-yacc.l"
return(DOT);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 209 "standard-pascal-no-yacc.l"
return(DOTDOT);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 210 "standard-pascal-no-yacc.l"
return(EQUAL);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 211 "standard-pascal-no-yacc.l"
return(notEQUAL);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 212 "standard-pascal-no-yacc.l"
return(GE);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 213 "standard-pascal-no-yacc.l"
return(GT);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 214 "standard-pascal-no-yacc.l"
return(LBRAC);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 215 "standard-pascal-no-yacc.l"
return(LE);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 216 "standard-pascal-no-yacc.l"
return(LPAREN);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 217 "standard-pascal-no-yacc.l"
return(LT);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 218 "standard-pascal-no-yacc.l"
return(MINUS);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 220 "standard-pascal-no-yacc.l"
return(PLUS);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 221 "standard-pascal-no-yacc.l"
return(RBRAC);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "standard-pascal-no-yacc.l"
return(RPAREN);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 224 "standard-pascal-no-yacc.l"
return(SEMICOLON);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 225 "standard-pascal-no-yacc.l"
return(SLASH);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 226 "standard-pascal-no-yacc.l"
return(STAR);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 227 "standard-pascal-no-yacc.l"
return(STARSTAR);
	YY_BREAK
case 71:
#line 230 "standard-pascal-no-yacc.l"
case 72:
YY_RULE_SETUP
#line 230 "standard-pascal-no-yacc.l"
{ register int c;
     while ((c = input()))
     {
      if (c == '}')
       break;
      else if (c == '*')
      {
       if ((c = input()) == ')')
        break;
       else
        unput (c);
      }
      else if (c == '\n')
       line_no++;
      else if (c == 0)
        fprintf (stdout, " Unexpected EOF inside comment at line %d\n",line_no);
     }
    }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 249 "standard-pascal-no-yacc.l"
;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 251 "standard-pascal-no-yacc.l"
;
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 252 "standard-pascal-no-yacc.l"
line_no++;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 255 "standard-pascal-no-yacc.l"
{fprintf(stdout, "%3d-th token  type: -error- \t on line %d : [%s] # Lexical analyzer error! \n", i,line_no, yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "standard-pascal-no-yacc.l"
ECHO;
	YY_BREAK
#line 1457 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 286 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 286 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 285);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 257 "standard-pascal-no-yacc.l"



int main(int argc, char** argv) {
  int tok;
  yyin = fopen(argv[1], "r");
  for (i = 0; 1==1; i ++) {
    tok = yylex();

	char *type_name = "type      ";
	int t_name;
	t_name = get_type_name(tok, &type_name);

    if(tok == CROSS_LINE_STRING)
    {
        fprintf(stdout, "%3d-th token  type: -error- \t on line %d : # invalid cross line string!\n", i, line_no);
    }
	else if(tok != COMMENT)
	{
		if (t_name)
			fprintf(stdout, "%3d-th token  type: [%s] \t on line %d : %s\n", i, type_name,line_no, yytext);
		else
			fprintf(stdout, "%3d-th token  type: [%d] \t on line %d : %s\n", i, tok,line_no, yytext);
	}
	else
        fprintf(stdout, "%3d-th token  type: [comment] \t on line %d : [This is a comment]\n", i, line_no);
        /*fprintf(stdout, "%3d-th token on line %d is a comment\n", i, line_no);*/
  }
  return(0);
} /* end of main */


int get_type_name(int tok, char **name)
{
	switch(tok)
	{
		case 28:
			*name = "program";
			return true;
		case 39:
			*name = "id";
			return true;
		case 66:
			*name = "num";
			return true;
		case 41:
			*name = "char_str";
			return true;
		case 36:
			*name = "var";
			return true;
		case 2:
			*name = "array";
			return true;
		case 21:
			*name = "of";
			return true;
		case 67:
			*name = "integer";
			return true;
		case REAL:
			*name = "real";
			return true;
		case FUNCTION:
			*name = "funct";
			return true;
		case PROCEDURE:
			*name = "proc";
			return true;
		case PBEGIN:
			*name = "begin";
			return true;
		case END:
			*name = "end";
			return true;
		case ASSIGNMENT:
			*name = "assign";
			return true;
		case IF:
			*name = "if";
			return true;
		case THEN:
			*name = "then";
			return true;
		case ELSE:
			*name = "else";
			return true;
		case WHILE:
			*name = "while";
			return true;
		case DO:
			*name = "do";
			return true;
		case NOT:
			*name = "not";
			return true;
		case LPAREN:
			*name = " ( ";
			return true;
		case RPAREN:
			*name = " ) ";
			return true;
		case SEMICOLON:
			*name = " ; ";
			return true;
		case DOT:
			*name = "dot";
			return true;
		case COMMA:
			*name = " , ";
			return true;
		case COLON:
			*name = " : ";
			return true;
		case LBRAC:
			*name = "lbrac";
			return true;
		case RBRAC:
			*name = "rbrac";
			return true;
		case LT:
			*name = " < ";
			return true;
		case LE:
			*name = " <= ";
			return true;
		case GT:
			*name = " > ";
			return true;
		case GE:
			*name = " >= ";
			return true;
		case EQUAL:
			*name = "equal";
			return true;
		case notEQUAL:
			*name = " != ";
			return true;
		case PLUS:
			*name = "plus";
			return true;
		case MINUS:
			*name = "minus";
			return true;
		case STAR:
			*name = "mul";
			return true;
		case SLASH:
			*name = "divide";
			return true;
		case DOTDOT:
			*name = " .. ";
			return true;
        case CROSS_LINE_STRING:
			*name = "run_str";
			return true;

		default:
			*name = "undefine";
			return false;
	}
}


comment()
{
	char c;

	while ((c = input()) != '\n' && c != 0)
	{}
}

yywrap() {
  fclose(yyin);
  exit(1);
}

